services:
  serveur:
    build:
      context: .
      dockerfile: Dockerfile.serveur
    container_name: serveur1
    ports:
      - "5000:5000"
    volumes:
      - ./taches.json:/app/taches.json
    restart: unless-stopped
    networks:
      - appnet

  client1:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: client1-1
    depends_on:
      - serveur
    stdin_open: true
    tty: true
    networks:
      - appnet

  client2:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: client2-1
    depends_on:
      - serveur
    stdin_open: true
    tty: true
    networks:
      - appnet

networks:
  appnet:
